### ISSUE TITLE
Emit `PaymentReceived` on upstream `PaymentReceived` or `PaymentClaimed`?

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/ldk-lite#34]
Having `PaymentReceived` *and* `PaymentClaimed` in LDK Lite might be a bit verbose for the 'simplified' API.

If we only want to have one, i.e., `PaymentReceived` event, it raises the question when we should emit it: on receiving  `PaymentReceived` or `PaymentClaimed`?

Or do we want to mirror both events here after all?

**Comment by valentinewallace** [comment]
> For the record, I'd find using something along the lines of PaymentIncoming / PaymentReceived also more intuitive than PaymentReceived/PaymentClaimed upstream, since PaymentReceived sounds pretty final by itself, even though it's actually not.

+1, I've gotten similar feedback about `PaymentReceived` being a confusing name

**Comment by tnull** [comment]
> +1, I've gotten similar feedback about `PaymentReceived` being a confusing name

Thanks, good to know, then maybe the solution could indeed be renaming the upstream event..

**Comment by tnull** [comment]
> Any suggestions for a better one? We should totally rename it upstream if it makes sense.

As mentioned above (in an edit), maybe something along the lines of 
`PaymentReceived` -> `PaymentIncoming` / `PaymentInbound`
`PaymentClaimed` -> `PaymentReceived`?

**Comment by valentinewallace** [comment]
`PaymentClaimable`? But I'm fine with all the above too^

**Comment by tnull** [comment]
> `PaymentClaimable`? But I'm fine with all the above too^

Ah, that's even better! Now the only thing is that the migration `PaymentClaimed`->`PaymentReceived` might be a pitfall for users as their code for the former `PaymentReceived` event might just keep on working for the wrong event without them noticing.

**Comment by tnull** [comment]
> Any of those SGTM, feel free to PR :)

Alright, will open a PR tomorrow/in the next days!

**Comment by tnull** [comment]
Closing as clarified, will update after upstream event has been merged.
